# -*- coding: utf-8 -*-
"""music_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19JL1fusolRxk-QE4auYw9wncXALHan-w
"""

#importing the module that will help with randomization of the notes
import random

def music_game(): 
    
    #Assigning a list of notes to the variable note_names
    notes = ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#']

    #random.choice(note_names) will choose a random note from note_names list and assign it to note1 & note2
    note1 = random.choice(notes)
    note2 = random.choice(notes)
    
    #Whenever note1 is equal to note2, note2 will be randomized until its not equal to note2
    while note1 == note2: 
        note2 = random.choice(notes)

    #Using string formatting to print value of randomly selected note1 & note2
    print('\n')
    print(f'What is the number of semitones between {note1} and {note2}?\n')
 
    #While loop ensures that the user inputs a valid interger othwerwise will not allow user to play the game until they put a number
    while True:
        try: 
            feedback = int(input('Enter your guess:\n'))
            break 
        except ValueError: 
            print('Enter a number.\n')
     
    #The position of any note is the index of the note plus 1, eg note_names.index('A') is 0, but position is 1
    answer = abs(notes.index(note1) - notes.index(note2)) - 1
        
    if feedback == answer: 
        print('\nYour answer is correct.\n')
    else: 
        print('\nYour guess is incorrect.\n')
        
    while True: 
        play_again = input('Do you wish to play again: Yes/No.\n')
        if play_again.upper() == 'YES':
            music_game()
            break 
        
        elif play_again.upper() == 'NO': 
            quit = input('\nAre you sure you want to quit: Yes/No.\n')
            if quit.upper() == 'YES': 
                print(f'\nThanks for playing, the correct answer is {answer}.\n')
                break
            else:
                quit.upper() == 'N'
                music_game()
                break 
        else: 
            print('Please enter Yes or No.\n')
        

#Execute the function      
music_game()

